### PR TITLE
Fix #[schemars(with = ...)] alongside #[serde(transparent)]

### PR DESCRIPTION
**Pull request by dimbleby**
`#typedef` is not allowed in that position:
```
error: struct is not supported in `trait`s or `impl`s
```

(diff is easier to read ignoring whitespace: append `?w=1` to the url).

I'd love a patch release including this fix, if that's possible.

(My motivation is that I want a string field that has a `pattern`, so I'm doing something like:
```
#[serde(transparent)]
pub struct StringWithMyPattern(#[schemars(schema_with = "string_with_my_pattern")] pub String);
```

I see that #12 considers cleaner approaches - something like `#[schemars(pattern = "regex")]` would be good for me.  I considered trying to make progress on implementing that, but to be honest I wasn't sure how to get started)

### CODE REVIEW

**Comment by dimbleby** [comment]
Ugh, underscore_const_names was stabilized in 1.37.0.

Do I need to find another way to write this, or can I just bump the minimum supported version?

**Comment by dimbleby** [comment]
I see that #68 is failing CI at 1.36 for the same reason

**Comment by GREsau** [comment]
Thanks @dimbleby!

**Comment by GREsau** [comment]
This is now in the latest version on crates.io - https://crates.io/crates/schemars/0.8.1

**Pull request merged**
