### PR TITLE
Add support for rust_decimal and bigdecimal

### PR DESCRIPTION
**Pull request by timando**

### CODE REVIEW

**Comment by rudolphfroger-ds** [comment]
Would be really nice to get this merged!

**Comment by rudolphfroger-ds** [comment]
Is there anything I can do to help get support for decimal support?

**Comment by GREsau** [comment]
Thanks, this is now published in v0.8.8 :)

**Comment by ghazalrashno** [comment]
HI,
I have updated to 0.8.8 but still get the error 
 
Cargo.toml:
```

[dependencies]
bigdecimal = { version = "0.1.2", features = ["serde"] }
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std", "serde"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "chrono", "numeric"] }
diesel-derive-enum = { version = "1.1.1", features = ["postgres"] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket_okapi = { version = "0.8.0-rc.1", features = ["swagger", "rapidoc"] }
rocket_sync_db_pools = { version = "0.1.0-rc.1", features = ["diesel_postgres_pool"] }
schemars = { version = "0.8.8", features = ["chrono", "bigdecimal"] }


[features]

```
My model:

 
```
use rocket::serde::{Serialize, Deserialize};
// use rocket_okapi::okapi::schemars;
// use rocket_okapi::okapi::schemars::JsonSchema; 
use chrono::{ NaiveDateTime };
use bigdecimal::BigDecimal;
use schemars::JsonSchema;

use crate::schema::*;  

#[derive( Debug, Deserialize, Serialize, AsChangeset, JsonSchema, Queryable, Associations)]
#[serde(crate = "rocket::serde")] 
#[table_name="products"]
pub struct Product {
    pub id: i32,
    
    pub name: String,
    pub name_mobile: Option<String>,  
    pub price: BigDecimal,

    pub size_id: Option<i32>,
    pub standard_id:Option<i32>,
    pub weight_id :Option<i32>,
    pub width_id :Option<i32>,
    pub diameter_id :Option<i32>,
    pub thickness_id :Option<i32>,
    pub factory_id :Option<i32>,
    pub loading_id :Option<i32>,

    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

```

Stack trace:

```

error[E0277]: the trait bound `BigDecimal: JsonSchema` is not satisfied
  --> src/api/model.rs:20:16
   |
20 |     pub price: BigDecimal,
   |                ^^^^^^^^^^ the trait `JsonSchema` is not implemented for `BigDecimal`

error[E0277]: the trait bound `BigDecimal: JsonSchema` is not satisfied
   --> src/api/model.rs:12:55
    |
12  | #[derive( Debug, Deserialize, Serialize, AsChangeset, JsonSchema, Queryable, Associations)]
    |                                                       ^^^^^^^^^^ the trait `JsonSchema` is not implemented for `BigDecimal`
    |
note: required by `_schemars_private_is_option`
   --> /Users/amin/.cargo/registry/src/github.com-1ecc6299db9ec823/schemars-0.8.8/src/lib.rs:382:5
    |
382 |     fn _schemars_private_is_option() -> bool {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the derive macro `JsonSchema` (in Nightly builds, run with -Z macro-backtrace for more info)

```

did i miss something or it is just not published publicly?

**Comment by GREsau** [comment]
You're referencing bigdecimal 0.1.2, but schemars only references 0.3 which is not semver-compatible with 0.1.2

If possible, update your reference of bigdecimal to 0.3

**Pull request merged**
