### PR TITLE
Cover serde_json RawValue type by schemars

### PR DESCRIPTION
**Pull request by luke-biel**
Closes https://github.com/GREsau/schemars/issues/149

### CODE REVIEW

**Comment by luke-biel** [comment]
Should any change or tests be necessary, feel free to poke me

**Comment by luke-biel** [comment]
@GREsau any chance of reviewing this soon?

**Comment by gahag-cw** [comment]
@GREsau friendly reminder, any chance we get a review for this in the near future?

**Comment by GREsau** [comment]
Thanks!

**Pull request merged**
